#+title: Lens_r Blog Website
#+author: Rylan Lens Kellogg
#+description: Lens_r made a blogging website.
#+created: <2022-05-27 Fri>
#+OPTIONS: ^:{}

Lens_r's blog website is created within GNU Emacs. Most content is written in ~org-mode~, an outline document format, and converted to HTML using ~org-publish~, an Emacs package.

The source of the website may be found in the ~org~ subdirectory.

** Building

The included ~publish.el~ will populate the ~web~ subdirectory with servable contents.

Run it using the following shell command:
#+begin_src sh
  emacs --chdir path/to/this/folder --script publish.el
#+end_src

*** Testing

Because GitHub Pages hosts the site within a subdirectory of the main server (i.e. ~/lensr_blog_v1/~ is the base URL), it means that local and remote absolute URLs don't match. To fix this, the locally hosted version of the site is put within a matching subdirectory, that way URLs can be the same either way.

NOTE: Use any port, there is nothing special about ~8000~ other than that it probably won't be used by anything important.

For local testing, I recommend Python's =http.server=.
#+begin_src sh
  cd localbuild
  python -m http.server 8000
#+end_src

It is also fairly simple to get a PHP server up and running.
#+begin_src sh
  cd localbuild
  php -S localhost:8000
#+end_src
